#!/usr/bin/env python3
from __future__ import annotations

from vid_to_sub_app.cli import (
    FolderAwareScheduler,
    ProcessResult,
    apply_runtime_path_map_to_manifest,
    build_parser,
    build_run_manifest,
    default_whisper_cpp_model_path as _default_whisper_cpp_model_path,
    discover_videos,
    emit_progress_event,
    extract_audio_for_whisper_cpp,
    extract_json_array as _extract_json_array,
    fmt_seconds as _fmt_seconds,
    load_manifest_from_stdin,
    main,
    parse_srt,
    parse_whisper_cpp_progress_seconds,
    postprocess_translated_segments_openai_compatible,
    persist_folder_manifest_state,
    primary_output_exists as _primary_output_exists,
    probe_media_duration,
    process_one,
    resolve_device_fw as _resolve_device_fw,
    run_parallel,
    transcribe,
    transcribe_faster_whisper,
    transcribe_openai_whisper,
    transcribe_whisper_cpp,
    transcribe_whisperx,
    translate_segments_openai_compatible,
)
from vid_to_sub_app.cli.discovery import hash_video_folder
from vid_to_sub_app.shared.constants import (
    DEFAULT_BACKEND,
    DEFAULT_DEVICE,
    DEFAULT_FORMAT,
    DEFAULT_MODEL,
    ENV_FILE,
    ENV_POSTPROCESS_API_KEY,
    ENV_POSTPROCESS_BASE_URL,
    ENV_POSTPROCESS_MODEL,
    ENV_TRANSLATION_API_KEY,
    ENV_TRANSLATION_BASE_URL,
    ENV_TRANSLATION_MODEL,
    ENV_WHISPER_CPP_BIN,
    ENV_WHISPER_CPP_MODEL,
    EVENT_PREFIX,
    KNOWN_MODELS,
    MODEL_SEARCH_DIRS,
    ROOT_DIR as SCRIPT_DIR,
    SUPPORTED_FORMATS,
    VIDEO_EXTENSIONS,
    WHISPER_CLI_CANDIDATES,
)
from vid_to_sub_app.shared.env import (
    candidate_model_dirs as _candidate_model_dirs,
    discover_ggml_models,
    find_whisper_cpp_bin,
    find_whisper_cpp_model_path,
    load_env_file,
    load_project_env,
    parse_env_assignment as _parse_env_assignment,
    preferred_ggml_model_path,
    resolve_executable as _resolve_executable,
)

if __name__ == "__main__":
    raise SystemExit(main())
